######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 18 22:31:54 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += xml
# Input
HEADERS += myTableWidget.h \
gradient.h
FORMS += tableWidget.ui \
gradientSelector.ui
SOURCES += main.cpp myTableWidget.cpp \
gradient.cpp \
xml_handlers.cpp
DISTFILES += foo.xml

